apiVersion: batch/v1
kind: Job
metadata:
  name: stopwatch-job
spec:
  template:
    spec:
      containers:
      - name: stopwatch-job
        image: yash5090/stopwatch:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
